#  ___ ___ ___ _____ ___  _  _ ___   _   _  __   _   
# | _ \ __|_ _|_   _/ _ \| || / __| /_\ | |/ /  /_\  
# |   / _| | |  | || (_) | __ \__ \/ _ \| ' <  / _ \ 
# |_|_\___|___| |_| \___/|_||_|___/_/ \_\_|\_\/_/ \_\
#

add_newline = true

format = """
$env_var\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$line_break\
$character
"""

palette = 'reitohsaka'

[palettes.reitohsaka]
blue = '#1D99F3'
green = '#11D116'
red = '#ED1515'
white = '#FCFCFC'
rei = '#FE8686'
fedora = '#51A2DA'

[character]
success_symbol = '╰⎯'
error_symbol = '╰⎯'

[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
style = 'bold rei'
read_only_style = 'bold red'
read_only = '  '
format = '[||](bold white) [$path]($style)[$read_only]($read_only_style) '

[env_var]
disabled = false
variable = 'SHELL'
symbol = '╭╴'
format = '$symbol'

[git_branch]
style = 'bold blue'
format = '[||](bold white) [$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'bold rei'

[hostname]
disabled = false
ssh_only = false
style = 'bold rei'
format = '[||](bold white) [$hostname]($style) '

[os]
disabled = false
format = '[$symbol](bold fedora) '

[os.symbols]
Fedora = ''

[username]
disabled = false
show_always = true
style_user = 'bold rei'
format = '[||](bold white) [$user]($style) '
